[tool.poetry]
name = "todolist"
version = "0.1.0"
description = "ToDoList"
authors = ["Parsa Pourghasemi <pour8383@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
python-dotenv = "^1.0.1"

[tool.poetry.scripts]
todolist = "cli.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
